---
- name: Create kickstart config
  template:
    src: "kickstart.cfg.j2"
    dest: "{{ kickstart_iso_storage }}/iso/kickstart.cfg"
    mode: 0644

- name: Create custom ISO image
  command: >
    xorrisofs -U -r -v -T -J -joliet-long -V '{{ kickstart_iso_name }}' -volset '{{ kickstart_iso_name }}'
    -A '{{ kickstart_iso_name }}' -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4
    -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot -o ../image_custom.iso .
  args:
    chdir: "{{ kickstart_iso_storage }}/iso"
  when: true

- name: Copy custom ISO image and kickstart config to destination directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  loop:
    - {src: "{{ kickstart_iso_storage }}/image_custom.iso",
       dest: "{{ kickstart_iso_storage }}/{{ kickstart_iso_info.file_name }}{{ ('_'
              + (kickstart_iso_host.name|default(''))
              + '_')|replace('__','_') }}{{ kickstart_iso_host.ip|replace('.','-') }}.iso"}

- name: Delete custom ISO image and kickstart config
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ kickstart_iso_storage }}/image_custom.iso"
    - "{{ kickstart_iso_storage }}/iso/kickstart.cfg"
