---
- name: Get base ISO image file name and checksum
  set_fact:
    kickstart_iso_info: "{{ dict(file_name=(item.split('  ')[1]).split('.')[0], checksum=item.split('  ')[0]) }}"
  loop: "{{ lookup('url', kickstart_iso_check_url, wantlist=True) }}"
  when: item is search(kickstart_iso_type)
  changed_when: false

- name: Ensure kickstart ISO images not already exist
  find:
    paths: "{{ kickstart_iso_storage }}"
    patterns: "{{ kickstart_iso_info.file_name }}_*.iso"
  register: kickstart_iso_check

- name: Create kickstart ISO images
  block:

    - name: Ensure required system packages are present
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - 'wget'
        - 'gcc'
        - 'gcc-c++'
        - 'make'
      register: kickstart_iso_packages_install
      until: kickstart_iso_packages_install is succeeded
      retries: 3
      delay: 60

    - name: Ensure required xorriso CLT exists
      command: xorriso -version
      register: kickstart_iso_xorriso_check
      ignore_errors: true
      changed_when: false

    - name: Ensure ephemeral files and directories are empty
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: 0755
      loop:
        - {path: "{{ kickstart_iso_storage }}/image.iso", state: 'absent'}
        - {path: "{{ kickstart_iso_storage }}/iso", state: 'absent'}
        - {path: "{{ kickstart_iso_storage }}/iso", state: 'directory'}
        - {path: "{{ kickstart_iso_storage }}/xorriso", state: 'absent'}
        - {path: "{{ kickstart_iso_storage }}/xorriso", state: 'directory'}

    - name: Build xorriso CLT
      become: true
      shell: |
        cd '{{ kickstart_iso_storage }}/xorriso'
        wget https://ftp.gnu.org/gnu/xorriso/xorriso-1.5.0.tar.gz
        tar xzf xorriso-1.5.0.tar.gz
        cd xorriso-1.5.0
        ./configure --prefix=/usr
        make
        ./xorriso/xorriso
        make buildstamped
        strip ./xorriso/xorriso
        make install
      when: kickstart_iso_xorriso_check is failed

    - name: Download base ISO image (support redirect)
      command: "wget {{ kickstart_iso_base_url }}{{ kickstart_iso_info.file_name }}.iso -O image.iso"
      args:
        chdir: "{{ kickstart_iso_storage }}"
        warn: false

    - name: Verify base ISO image
      command: "sha256sum image.iso"
      args:
        chdir: "{{ kickstart_iso_storage }}"
      register: kickstart_iso_verify
      failed_when: (kickstart_iso_verify.stdout).split('  ')[0] != kickstart_iso_info.checksum

    - name: Extract base ISO image
      command: xorriso -osirrox on -indev image.iso -extract / iso
      args:
        chdir: "{{ kickstart_iso_storage }}"

    - name: Edit Boot-Menu config to automatically run kickstart config
      lineinfile:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter }}"
        firstmatch: "{{ item.firstmatch }}"
      loop:
        - {path: "{{ kickstart_iso_storage }}/iso/{{ kickstart_iso_bios_conf_file }}", state: 'absent',
           regexp: '^  menu default', line: '', insertafter: EOF, firstmatch: false}
        - {path: "{{ kickstart_iso_storage }}/iso/{{ kickstart_iso_bios_conf_file }}", state: 'present',
           regexp: ".*{{ ('inst.stage2=hd:LABEL=' + kickstart_iso_boot_name + ' quiet')|regex_escape() }}",
           line: "  append initrd=initrd.img inst.ks=hd:LABEL={{ kickstart_iso_boot_name }}:/kickstart.cfg
                  inst.stage2=hd:LABEL={{ kickstart_iso_boot_name }} quiet",
           insertafter: EOF, firstmatch: false}
        - {path: "{{ kickstart_iso_storage }}/iso/{{ kickstart_iso_bios_conf_file }}", state: 'present',
           regexp: '^  menu default', line: '  menu default', insertafter: '^  menu label \^Install', firstmatch: true}
        - {path: "{{ kickstart_iso_storage }}/iso/{{ kickstart_iso_uefi_conf_file }}", state: 'present',
           regexp: '^set default=', line: 'set default="0"', insertafter: EOF, firstmatch: false}
        - {path: "{{ kickstart_iso_storage }}/iso/{{ kickstart_iso_uefi_conf_file }}", state: 'present',
           regexp: ".*{{ ('inst.stage2=hd:LABEL=' + kickstart_iso_boot_name + ' quiet')|regex_escape() }}",
           line: "        linuxefi /images/pxeboot/vmlinuz
                  inst.ks=hd:LABEL={{ kickstart_iso_boot_name }}:/kickstart.cfg
                  inst.stage2=hd:LABEL={{ kickstart_iso_boot_name }} quiet",
           insertafter: EOF, firstmatch: false}

    - name: Loop kickstart ISO image creation
      include_tasks: create.yml
      loop: "{{ (kickstart_iso_network_static_hosts|default([])) + [dict(ip=kickstart_iso_network_bootproto)] }}"
      loop_control:
        loop_var: kickstart_iso_host

    - name: Delete ephemeral files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ kickstart_iso_storage }}/image.iso"
        - "{{ kickstart_iso_storage }}/iso"
        - "{{ kickstart_iso_storage }}/xorriso"

  when: kickstart_iso_check.matched|int == 0
